### ISSUE TITLE
Colorless mode

### ISSUE THREAD

**Issue by Vilsol** [Skarlso/effrit#10]
There should be an option to disable coloring, otherwise the output is unreadable in certain terminals.

![https://i.imgur.com/I2j74rr.png](https://i.imgur.com/I2j74rr.png)

**Comment by Skarlso** [comment]
@Vilsol Hey! Thanks for this issue! Nice catch. :) Will do.

**Comment by Skarlso** [comment]
Now, as you'd expect from linux tools, color mode is something you'd enable and by default it's off. Is that okay?

**Comment by Vilsol** [comment]
That is much better, thank you!
