### ISSUE TITLE
Abstractness is calculated as over 1

### ISSUE THREAD

**Issue by Skarlso** [Skarlso/effrit#4]
`github.com/go-furnace/go-furnace/furnace-aws/config                           | 0.5       | 1.8          | 1.2`

This metric should also be between 0-1 🤔

**Comment by Skarlso** [comment]
Ah... It's because of the structs I'm counting towards being abstract.. There is a TODO right now to only count structs as abstract if they don't have any method receivers in the pkg. Currently that's not an easy task without using a regex, which I would like to avoid.

**Comment by egawata** [comment]
I'm afraid the abstractness should be calculated by `(abstract classes) / (all classes)`. So the problem would be solved by: 

~~~diff
diff --git a/pkg/packages.go b/pkg/packages.go
index e81acd2..07b8005 100644
--- a/pkg/packages.go
+++ b/pkg/packages.go
@@ -173,7 +173,7 @@ func (pkg *Packages) CalculateAbstractnessOfPackages() error {
                if funcCount == 0 {
                        funcCount = 1
                }
-               p.Abstractness = abstractsCount / funcCount
+               p.Abstractness = abstractsCount / (funcCount + abstractsCount)
                pkg.packageMap[k] = p
        } // packages
        return nil
~~~

https://kariera.future-processing.pl/blog/object-oriented-metrics-by-robert-martin/

**Comment by Skarlso** [comment]
Neat! :) Thanks. :) I'll submit a fix.
